# DO NOT COMMIT TO GIT or GITHUB REPOSITORIES
# SECURE and LOCAL INFO
#############################################

EMAIL_HOST = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
